package report

// FeedMetric 信息流指标
type FeedMetric struct {
	// TransPrice 目标转化成本
	TransPrice float64 `json:"transPrice,omitempty"`
	// PhoneButtonClicks 点击创意组件button次数
	PhoneButtonClicks int64 `json:"phoneButtonClicks,omitempty"`
	// Interaction 用户对广告的交互操作，对视频广告，互动行为包含点击互动和有效播放互动，对其它格式的广告互动依然仅包含点击
	Interaction int64 `json:"interaction,omitempty"`
	// OcpcTargetTrans 目标转化量
	OcpcTargetTrans int64 `json:"ocpcTargetTrans,omitempty"`
	// OcpcTargetTransCPC 目标转化成本
	OcpcTargetTransCPC float64 `json:"ocpcTargetTransCPC,omitempty"`
	// OcpcTargetTransRatio 目标转化率
	OcpcTargetTransRatio float64 `json:"ocpcTargetTransRatio,omitempty"`
	// OcpcDeepTargetTrans 	深度转化量
	OcpcDeepTargetTrans int64 `json:"ocpcDeepTargetTrans,omitempty"`
	// OcpcDeepTargetTransCPC 	深度转化成本
	OcpcDeepTargetTransCPC float64 `json:"ocpcDeepTargetTransCPC,omitempty"`
	// OcpcDeepTargetTransRatio 	深度转化率
	OcpcDeepTargetTransRatio float64 `json:"ocpcDeepTargetTransRatio,omitempty"`
	// ConvertTimeOCPCTargetTrans 目标转化量（转化时间）
	ConvertTimeOCPCTargetTrans int64 `json:"convertTimeOCPCTargetTrans,omitempty"`
	// ConvertTimeOCPCDeepTargetTrans 深度目标转化量（转化时间）
	ConvertTimeOCPCDeepTargetTrans int64 `json:"convertTimeOCPCDeepTargetTrans,omitempty"`
	// LandingPageDurationSec 访问时长
	LandingPageDurationSec int64 `json:"landingPageDurationSec,omitempty"`
	// 落地页转化 相关
	// AggrFormSubmitSuccess 表单提交成功量
	AggrFormSubmitSuccess int64 `json:"aggrFormSubmitSuccess,omitempty"`
	// AggrFormSubmitSuccessCost 表单提交成功成本
	AggrFormSubmitSuccessCost float64 `json:"aggrFormSubmitSuccessCost,omitempty"`
	// AggrFormSubmitSuccessCVR 表单提交成功转化率
	AggrFormSubmitSuccessCVR float64 `json:"aggrFormSubmitSuccessCVR,omitempty"`
	// AggrFormClickSuccess 表单按钮点击量
	AggrFormClickSuccess int64 `json:"aggrFormClickSuccess,omitempty"`
	// AggrFormClickSuccessCost 表单按钮点击成本
	AggrFormClickSuccessCost float64 `json:"aggrFormClickSuccessCost,omitempty"`
	// AggrFormClickSuccessCVR 表单按钮点击转化率
	AggrFormClickSuccessCVR float64 `json:"aggrFormClickSuccessCVR,omitempty"`
	// AggrOrderSubmitSuccess 订单提交成功量
	AggrOrderSubmitSuccess int64 `json:"aggrOrderSubmitSuccess,omitempty"`
	// AggrOrderSubmitSuccessCost 订单提交成功成本
	AggrOrderSubmitSuccessCost float64 `json:"aggrOrderSubmitSuccessCost,omitempty"`
	// AggrOrderSubmitSuccessCVR 订单提交成功转化率
	AggrOrderSubmitSuccessCVR float64 `json:"aggrOrderSubmitSuccessCVR,omitempty"`
	// AggrOrderSubmitSuccessAmount 订单提交成功金额
	AggrOrderSubmitSuccessAmount float64 `json:"aggrOrderSubmitSuccessAmount,omitempty"`
	// AggrOrderSubmitSuccessAmountROI 订单提交成功ROI
	AggrOrderSubmitSuccessAmountROI float64 `json:"aggrOrderSubmitSuccessAmountROI,omitempty"`
	// AggrReverseClicks 表单调起按钮点击量
	AggrReverseClicks int64 `json:"aggrReverseClicks,omitempty"`
	// AggrReverseClicksCost 表单调起按钮点击成本
	AggrReverseClicksCost float64 `json:"aggrReverseClicksCost,omitempty"`
	// AggrReverseClicksCVR 表单调起按钮点击转化率
	AggrReverseClicksCVR float64 `json:"aggrReverseClicksCVR,omitempty"`
	// EffectiveConsult 一句话咨询量
	EffectiveConsult int64 `json:"effectiveConsult,omitempty"`
	// EffectiveConsultCost 一句话咨询成本
	EffectiveConsultCost float64 `json:"effectiveConsultCost,omitempty"`
	// EffectiveConsultCVR 一句话咨询转化率
	EffectiveConsultCVR float64 `json:"effectiveConsultCVR,omitempty"`
	// AggrEffectiveConsults 一句话咨询量
	AggrEffectiveConsults int64 `json:"aggrEffectiveConsults,omitempty"`
	// AggrEffectiveConsultsCost 一句话咨询成本
	AggrEffectiveConsultsCost float64 `json:"aggrEffectiveConsultsCost,omitempty"`
	// AggrEffectiveConsultsCVR 一句话咨询转化率
	AggrEffectiveConsultsCVR float64 `json:"aggrEffectiveConsultsCVR,omitempty"`
	// HighQualityConsults 三句话咨询量
	HighQualityConsults int64 `json:"highqualityConsults,omitempty"`
	// HighQualityConsultsCost 三句话咨询成本
	HighQualityConsultsCost float64 `json:"highqualityConsultsCost,omitempty"`
	// HighQualityConsultsCVR 三句话咨询转化率
	HighQualityConsultsCVR float64 `json:"highqualityConsultsCVR,omitempty"`
	// AggrConsultClicks 咨询按钮点击量
	AggrConsultClicks int64 `json:"aggrConsultClicks,omitempty"`
	// AggrConsultClicksCost 咨询按钮点击成本
	AggrConsultClicksCost float64 `json:"aggrConsultClicksCost,omitempty"`
	// AggrConsultClicksCVR 咨询按钮点击转化率
	AggrConsultClicksCVR float64 `json:"aggrConsultClicksCVR,omitempty"`
	// AggrPhoneClicks 电话按钮点击量
	AggrPhoneClicks int64 `json:"aggrPhoneClicks,omitempty"`
	// AggrPhoneClicksCost 电话按钮点击成本
	AggrPhoneClicksCost float64 `json:"aggrPhoneClicksCost,omitempty"`
	// AggrPhoneClicksCVR 电话按钮点击转化率
	AggrPhoneClicksCVR float64 `json:"aggrPhoneClicksCVR,omitempty"`
	// AggrPageViews 营销页浏览量
	AggrPageViews int64 `json:"aggrPageViews,omitempty"`
	// EffectiveClient 客户自定义转化量
	EffectiveClient int64 `json:"effectiveClient,omitempty"`
	// EffectiveClientCost 客户自定义转化成本
	EffectiveClientCost float64 `json:"effectiveClientCost,omitempty"`
	// EffectiveClientCVR 客户自定义转化率
	EffectiveClientCVR float64 `json:"effectiveClientCVR,omitempty"`
	// WeixinCopyConversions 微信复制按钮点击量
	WeixinCopyConversions int64 `json:"weiXinCopyConversions,omitempty"`
	// WeixinCopyConversionsCost 微信复制按钮点击成本
	WeixinCopyConversionsCost float64 `json:"weiXinCopyConversionsCost,omitempty"`
	// WeixinCopyConversionsCVR 微信复制按钮点击转化率
	WeixinCopyConversionsCVR float64 `json:"weiXinCopyConversionsCVR,omitempty"`
	// OrderCheck 订单核对成功量
	OrderCheck int64 `json:"orderCheck,omitempty"`
	// OrderCheckCost 订单核对成功成本
	OrderCheckCost float64 `json:"orderCheckCost,omitempty"`
	// OrderCheckCVR 订单核对成功转化率
	OrderCheckCVR float64 `json:"orderCheckCVR,omitempty"`
	// Receives 收货成功量
	Receives int64 `json:"receives,omitempty"`
	// ReceivesCost 收货成功成本
	ReceivesCost float64 `json:"receivesCost,omitempty"`
	// ReceivesCVR 收货成功转化率
	ReceivesCVR float64 `json:"receivesCVR,omitempty"`
	// EcBuy 商品下单成功量
	EcBuy int64 `json:"ecBuy,omitempty"`
	// EcBuyCost 商品下单成功成本
	EcBuyCost float64 `json:"ecBuyCost,omitempty"`
	// EcBuyCVR 商品下单成功转化率
	EcBuyCVR float64 `json:"ecBuyCVR,omitempty"`
	// EcPageArrival 商品详情页达到量
	EcPageArrival int64 `json:"ecPageArrival,omitempty"`
	// EcPageArrivalCost 商品详情页达到成本
	EcPageArrivalCost float64 `json:"ecPageArrivalCost,omitempty"`
	// EcPageArrivalCVR 商品详情页达到转化率
	EcPageArrivalCVR float64 `json:"ecPageArrivalCVR,omitempty"`
	// EcPaidSuccess 服务购买成功量
	EcPaidSuccess int64 `json:"ecPaidSuccess,omitempty"`
	// EcPaidSuccessCost 服务购买成功成本
	EcPaidSuccessCost float64 `json:"ecPaidSuccessCost,omitempty"`
	// EcPaidSuccessCVR 服务购买成功转化率
	EcPaidSuccessCVR float64 `json:"ecPaidSuccessCVR,omitempty"`
	// InvokingAppConversions 店铺调起量
	InvokingAppConversions int64 `json:"invokingAppConversions,omitempty"`
	// InvokingAppConversionsCost 店铺调起成本
	InvokingAppConversionsCost float64 `json:"invokingAppConversionsCost,omitempty"`
	// InvokingAppConversionsCVR 店铺调起转化率
	InvokingAppConversionsCVR float64 `json:"invokingAppConversionsCVR,omitempty"`
	// ReturnOnInvestment 广告支出回报率（ROI）
	ReturnOnInvestment float64 `json:"returnOnInvestment,omitempty"`
	// WeixinAppButtonConversions 微信调起按钮点击量
	WeixinAppButtonConversions int64 `json:"weiXinAppButtonConversions,omitempty"`
	// WeixinAppButtonConversionsCost 微信调起按钮点击成本
	WeixinAppButtonConversionsCost float64 `json:"weiXinAppButtonConversionsCost,omitempty"`
	// WeixinAppButtonConversionsCVR 微信调起按钮点击转化率
	WeixinAppButtonConversionsCVR float64 `json:"weiXinAppButtonConversionsCVR,omitempty"`
	// FansFellowSuccessConversions 粉丝关注成功量
	FansFellowSuccessConversions int64 `json:"fansFellowSuccessConversions,omitempty"`
	// FansFellowSuccessConversionsCost 粉丝关注成功成本
	FansFellowSuccessConversionsCost float64 `json:"fansFellowSuccessConversionsCost,omitempty"`
	// FansFellowSuccessConversionsCVR 粉丝关注成功转化率
	FansFellowSuccessConversionsCVR float64 `json:"fansFellowSuccessConversionsCVR,omitempty"`
	// Registers 注册人数
	Registers int64 `json:"registers,omitempty"`
	// RegistersCost 注册成本
	RegistersCost float64 `json:"registersCost,omitempty"`
	// RegistersCVR 注册转化率
	RegistersCVR float64 `json:"registersCVR,omitempty"`
	// Applications 申请量
	Applications int64 `json:"applications,omitempty"`
	// ApplicationsCost 申请成本
	ApplicationsCost float64 `json:"applicationsCost,omitempty"`
	// ApplicationsCVR 申请转化率
	ApplicationsCVR float64 `json:"applicationsCVR,omitempty"`
	// Credits 授信量
	Credits int64 `json:"credits,omitempty"`
	// CreditsCost 授信成本
	CreditsCost float64 `json:"creditsCost,omitempty"`
	// CreditsCVR 授信转化率
	CreditsCVR float64 `json:"creditsCVR,omitempty"`
	// AdvisoryClueCount 留线索量
	AdvisoryClueCount int64 `json:"advisoryClueCount,omitempty"`
	// AdvisoryClueCountCost 留线索成本
	AdvisoryClueCountCost float64 `json:"advisoryClueCountCost,omitempty"`
	// AdvisoryClueCountCVR 留线索转化率
	AdvisoryClueCountCVR float64 `json:"advisoryClueCountCVR,omitempty"`
	// EcShoppingCart 加入购物车量
	EcShoppingCart int64 `json:"ecShoppingCart,omitempty"`
	// EcShoppingCartCost 加入购物车成本
	EcShoppingCartCost float64 `json:"ecShoppingCartCost,omitempty"`
	// EcShoppingCartCVR 加入购物车转化率
	EcShoppingCartCVR float64 `json:"ecShoppingCartCVR,omitempty"`
	// EcFaviorite 商品收藏量
	EcFaviorite int64 `json:"ecFaviorite,omitempty"`
	// EcFavioriteCost 商品收藏成本
	EcFavioriteCost float64 `json:"ecFavioriteCost,omitempty"`
	// EcFavioriteCVR 商品收藏转化率
	EcFavioriteCVR float64 `json:"ecFavioriteCVR,omitempty"`
	// ReserveDownloadConversions 下载（预约）按钮点击量
	ReserveDownloadConversions int64 `json:"reserveDownloadConversions,omitempty"`
	// ReserveDownloadConversionsCost 下载（预约）按钮点击成本
	ReserveDownloadConversionsCost float64 `json:"reserveDownloadConversionsCost,omitempty"`
	// ReserveDownloadConversionsCVR 下载（预约）按钮点击转化率
	ReserveDownloadConversionsCVR float64 `json:"reserveDownloadConversionsCVR,omitempty"`
	// PhoneDialUpConversions 电话拨通量
	PhoneDialUpConversions int64 `json:"phoneDialUpConversions,omitempty"`
	// PhoneDialUpConversionsCost 电话拨通成本
	PhoneDialUpConversionsCost float64 `json:"phoneDialUpConversionsCost,omitempty"`
	// PhoneDialUpConversionsCVR 电话拨通转化率
	PhoneDialUpConversionsCVR float64 `json:"phoneDialUpConversionsCVR,omitempty"`
	// StoreStayConversions 店铺停留转化量
	StoreStayConversions int64 `json:"storeStayConversions,omitempty"`
	// StoreStayConversionsCost 店铺停留成本
	StoreStayConversionsCost float64 `json:"storeStayConversionsCost,omitempty"`
	// StoreStayConversionsCVR 店铺停留转化率
	StoreStayConversionsCVR float64 `json:"storeStayConversionsCVR,omitempty"`
	// LiveWatchConversions 直播间观看量
	LiveWatchConversions int64 `json:"liveWatchConversions,omitempty"`
	// LiveWatchConversionsCost 直播间观看成本
	LiveWatchConversionsCost float64 `json:"liveWatchConversionsCost,omitempty"`
	// LiveWatchConversionsCVR 直播间观看转化率
	LiveWatchConversionsCVR float64 `json:"liveWatchConversionsCVR,omitempty"`
	// LiveOrderConversions 直播间成单量
	LiveOrderConversions int64 `json:"liveOrderConversions,omitempty"`
	// LiveOrderConversionsCost 直播间成单成本
	LiveOrderConversionsCost float64 `json:"liveOrderConversionsCost,omitempty"`
	// LiveOrderConversionsCVR 直播间成单转化率
	LiveOrderConversionsCVR float64 `json:"liveOrderConversionsCVR,omitempty"`
	// LiveProductClickConversions 直播间商品按钮点击量
	LiveProductClickConversions int64 `json:"liveProductClickConversions,omitempty"`
	// LiveProductClickConversionsCost 直播间商品按钮点击成本
	LiveProductClickConversionsCost float64 `json:"liveProductClickConversionsCost,omitempty"`
	// LiveProductClickConversionsCVR 直播间商品按钮点击转化率
	LiveProductClickConversionsCVR float64 `json:"liveProductClickConversionsCVR,omitempty"`
	// LiveStayConversions 直播间停留量
	LiveStayConversions int64 `json:"liveStayConversions,omitempty"`
	// LiveStayConversionsCost 直播间停留成本
	LiveStayConversionsCost float64 `json:"liveStayConversionsCost,omitempty"`
	// LiveStayConversionsCVR 直播间停留转化率
	LiveStayConversionsCVR float64 `json:"liveStayConversionsCVR,omitempty"`
	// LiveCommentConversions 直播间评论量
	LiveCommentConversions int64 `json:"liveCommentConversions,omitempty"`
	// LiveCommentConversionsCost 直播间评论成本
	LiveCommentConversionsCost float64 `json:"liveCommentConversionsCost,omitempty"`
	// LiveCommentConversionsCVR 直播间评论转化率
	LiveCommentConversionsCVR float64 `json:"liveCommentConversionsCVR,omitempty"`
	// LiveRewardConversions 直播间打赏量
	LiveRewardConversions int64 `json:"liveRewardConversions,omitempty"`
	// LiveRewardConversionsCost 直播间打赏成本
	LiveRewardConversionsCost float64 `json:"liveRewardConversionsCost,omitempty"`
	// LiveRewardConversionsCVR 直播间打赏转化率
	LiveRewardConversionsCVR float64 `json:"liveRewardConversionsCVR,omitempty"`
	// LiveShoppingBagClickConversions 直播间购物袋点击量
	LiveShoppingBagClickConversions int64 `json:"liveShoppingBagClickConversions,omitempty"`
	// LiveShoppingBagClickConversionsCost 直播间购物袋点击成本
	LiveShoppingBagClickConversionsCost float64 `json:"liveShoppingBagClickConversionsCost,omitempty"`
	// LiveShoppingBagClickConversionsCVR 直播间购物袋点击转化率
	LiveShoppingBagClickConversionsCVR float64 `json:"liveShoppingBagClickConversionsCVR,omitempty"`
	// WeixinFollowSuccessConversions 微信加粉成功量
	WeixinFollowSuccessConversions int64 `json:"weixinFollowSuccessConversions,omitempty"`
	// WeixinFollowSuccessConversionsCost 微信加粉成功成本
	WeixinFollowSuccessConversionsCost float64 `json:"weixinFollowSuccessConversionsCost,omitempty"`
	// WeixinFollowSuccessConversionsCVR 微信加粉成功转化率
	WeixinFollowSuccessConversionsCVR float64 `json:"weixinFollowSuccessConversionsCVR,omitempty"`
	// ProductPaySuccess 商品支付成功量
	ProductPaySuccess int64 `json:"productPaySuccess,omitempty"`
	// ProductPaySuccessCost 商品支付成功成本
	ProductPaySuccessCost float64 `json:"productPaySuccessCost,omitempty"`
	// ProductPaySuccessCVR 商品支付成功转化率
	ProductPaySuccessCVR float64 `json:"productPaySuccessCVR,omitempty"`
	// ProductPaySuccessAmount 商品支付成功金额
	ProductPaySuccessAmount float64 `json:"productPaySuccessAmount,omitempty"`
	// ProductPaySuccessAmountROI 商品支付成功ROI
	ProductPaySuccessAmountROI float64 `json:"productPaySuccessAmountROI,omitempty"`
	// VisitStore 到店量
	VisitStore int64 `json:"visitStore,omitempty"`
	// VisitStoreCost 到店成本
	VisitStoreCost float64 `json:"visitStoreCost,omitempty"`
	// VisitStoreCVR 到店转化率
	VisitStoreCVR float64 `json:"visitStoreCVR,omitempty"`
	// TalkRelatedBusiness 聊到相关业务量
	TalkRelatedBusiness int64 `json:"talkRelatedBusiness,omitempty"`
	// TalkRelatedBusinessCost 聊到相关业务成本
	TalkRelatedBusinessCost float64 `json:"talkRelatedBusinessCost,omitempty"`
	// TalkRelatedBusinessCVR 聊到相关业务转化率
	TalkRelatedBusinessCVR float64 `json:"talkRelatedBusinessCVR,omitempty"`
	// ReturnVisitPhoneConnect 回访-电话接通量
	ReturnVisitPhoneConnect int64 `json:"returnVisitPhoneConnect,omitempty"`
	// ReturnVisitPhoneConnectCost 回访-电话接通成本
	ReturnVisitPhoneConnectCost float64 `json:"returnVisitPhoneConnectCost,omitempty"`
	// ReturnVisitPhoneConnectCVR 回访-电话接通转化率
	ReturnVisitPhoneConnectCVR float64 `json:"returnVisitPhoneConnectCVR,omitempty"`
	// ReturnVisitInformationConfirm 回访-信息确认量
	ReturnVisitInformationConfirm int64 `json:"returnVisitInformationConfirm,omitempty"`
	// ReturnVisitInformationConfirmCost 回访-信息确认成本
	ReturnVisitInformationConfirmCost float64 `json:"returnVisitInformationConfirmCost,omitempty"`
	// ReturnVisitInformationConfirmCVR 回访-信息确认转化率
	ReturnVisitInformationConfirmCVR float64 `json:"returnVisitInformationConfirmCVR,omitempty"`
	// ReturnVisitFoundIntention 回访-发现意向量
	ReturnVisitFoundIntention int64 `json:"returnVisitFoundIntention,omitempty"`
	// ReturnVisitFoundIntentionCost 回访-发现意向成本
	ReturnVisitFoundIntentionCost float64 `json:"returnVisitFoundIntentionCost,omitempty"`
	// ReturnVisitFoundIntentionCVR 回访-发现意向转化率
	ReturnVisitFoundIntentionCVR float64 `json:"returnVisitFoundIntentionCVR,omitempty"`
	// ReturnVisitHighPotentialDeal 回访-高潜成交量
	ReturnVisitHighPotentialDeal int64 `json:"returnVisitHighPotentialDeal,omitempty"`
	// ReturnVisitHighPotentialDealCost 回访-高潜成交成本
	ReturnVisitHighPotentialDealCost float64 `json:"returnVisitHighPotentialDealCost,omitempty"`
	// ReturnVisitHighPotentialDealCVR 回访-高潜成交转化率
	ReturnVisitHighPotentialDealCVR float64 `json:"returnVisitHighPotentialDealCVR,omitempty"`
	// ReturnVisitFinishOrderClient 回访-成单客户量
	ReturnVisitFinishOrderClient int64 `json:"returnVisitFinishOrderClient,omitempty"`
	// ReturnVisitFinishOrderClientCost 回访-成单客户成本
	ReturnVisitFinishOrderClientCost float64 `json:"returnVisitFinishOrderClientCost,omitempty"`
	// ReturnVisitFinishOrderClientCVR 回访-成单客户转化率
	ReturnVisitFinishOrderClientCVR float64 `json:"returnVisitFinishOrderClientCVR,omitempty"`
	// PayReadUv 付费阅读人数
	PayReadUv int64 `json:"payReadUv,omitempty"`
	// PayReadUvCost 付费阅读成本
	PayReadUvCost float64 `json:"payReadUvCost,omitempty"`
	// PayReadUvCVR 付费阅读转化率
	PayReadUvCVR float64 `json:"payReadUvCVR,omitempty"`
	// PayReadAmount 付费阅读金额
	PayReadAmount float64 `json:"payReadAmount,omitempty"`
	// PayReadAmountROI 付费阅读ROI
	PayReadAmountROI float64 `json:"payReadAmountROI,omitempty"`
	// ValidConsult 有效咨询量
	ValidConsult int64 `json:"validConsult,omitempty"`
	// ValidConsultCost 有效咨询成本
	ValidConsultCost float64 `json:"validConsultCost,omitempty"`
	// ValidConsultCVR 有效咨询转化率
	ValidConsultCVR float64 `json:"validConsultCVR,omitempty"`
	// JiMuYuReserveDownloadConversions JiMuYuReserveDownloadConversions
	JiMuYuReserveDownloadConversions int64 `json:"jiMuYuReserveDownloadConversions,omitempty"`
	// AggrPageViewsCost 营销页浏览成本
	AggrPageViewsCost float64 `json:"aggrPageViewsCost,omitempty"`
	// AggrPageViewsCVR 营销页浏览转化率
	AggrPageViewsCVR float64 `json:"aggrPageViewsCVR,omitempty"`
	// WeixinAppInvokeUv 微信小程序调起人数
	WeixinAppInvokeUv int64 `json:"weixinAppInvokeUv,omitempty"`
	// WeixinAppInvokeUvCost 微信小程序调起成本
	WeixinAppInvokeUvCost float64 `json:"weixinAppInvokeUvCost,omitempty"`
	// WeixinAppInvokeUvCVR 微信小程序调起转化率
	WeixinAppInvokeUvCVR float64 `json:"weixinAppInvokeUvCVR,omitempty"`
	// 落地页转化（转化时间）
	// CtAggrFormSubmitSuccess 表单提交成功量（转化时间）
	CtAggrFormSubmitSuccess int64 `json:"ctAggrFormSubmitSuccess,omitempty"`
	// CtAggrFormClickSuccess 表单按钮点击量（转化时间）
	CtAggrFormClickSuccess int64 `json:"ctAggrFormClickSuccess,omitempty"`
	// CtAggrOrderSubmitSuccess 订单提交成功量（转化时间）
	CtAggrOrderSubmitSuccess int64 `json:"ctAggrOrderSubmitSuccess,omitempty"`
	// CtAggrOrderSubmitSuccessAmount 订单提交成功金额（转化时间）
	CtAggrOrderSubmitSuccessAmount float64 `json:"ctAggrOrderSubmitSuccessAmount,omitempty"`
	// CtAggrOrderSubmitSuccessAmountROI 订单提交成功ROI（转化时间）
	CtAggrOrderSubmitSuccessAmountROI float64 `json:"ctAggrOrderSubmitSuccessAmountROI,omitempty"`
	// CtAggrReverseClicks 表单调起按钮点击量（转化时间）
	CtAggrReverseClicks int64 `json:"ctAggrReverseClicks,omitempty"`
	// CtAggrEffectiveConsults 一句话咨询量（转化时间）
	CtAggrEffectiveConsults int64 `json:"ctAggrEffectiveConsults,omitempty"`
	// CtAggrHighQualityConsults 三句话咨询量（转化时间）
	CtAggrHighQualityConsults int64 `json:"ctAggrHighqualityConsults,omitempty"`
	// CtAggrConsultClicks 咨询按钮点击量（转化时间）
	CtAggrConsultClicks int64 `json:"ctAggrConsultClicks,omitempty"`
	// CtAggrPhoneClicks 电话按钮点击量（转化时间）
	CtAggrPhoneClicks int64 `json:"ctAggrPhoneClicks,omitempty"`
	// CtAggrTongjiConversions 百度统计转化量（转化时间）
	CtAggrTongjiConversions int64 `json:"ctAggrTongjiConversions,omitempty"`
	// CtEffectiveClient 客户自定义转化量（转化时间）
	CtEffectiveClient int64 `json:"ctEffectiveClient,omitempty"`
	// CtWeixinCopyConversions 微信复制按钮点击量（转化时间）
	CtWeixinCopyConversions int64 `json:"ctWeiXinCopyConversions,omitempty"`
	// CtOrderCheck 订单核对成功量（转化时间）
	CtOrderCheck int64 `json:"ctOrderCheck,omitempty"`
	// CtReceives 收货成功量（转化时间）
	CtReceives int64 `json:"ctReceives,omitempty"`
	// CtECBuy 商品下单成功量（转化时间）
	CtECBuy int64 `json:"ctECBuy,omitempty"`
	// CtECPageArrival 商品详情页达到量（转化时间）
	CtECPageArrival int64 `json:"ctECPageArrival,omitempty"`
	// CtEcPaidSuccess 服务购买成功量（转化时间）
	CtEcPaidSuccess int64 `json:"ctEcPaidSuccess,omitempty"`
	// CtInvokingAppConversions 店铺调起量（转化时间）
	CtInvokingAppConversions int64 `json:"ctInvokingAppConversions,omitempty"`
	// CtReturnOnInvestment 广告支出回报率（ROI）（转化时间）
	CtReturnOnInvestment float64 `json:"ctReturnOnInvestment,omitempty"`
	// CtWeixinAppButtonConversions 微信调起按钮点击量（转化时间）
	CtWeixinAppButtonConversions int64 `json:"ctWeiXinAppButtonConversions,omitempty"`
	// CtFansFellowSuccessConversions 粉丝关注成功量（转化时间）
	CtFansFellowSuccessConversions int64 `json:"ctFansFellowSuccessConversions,omitempty"`
	// CtRegisters 注册人数（转化时间）
	CtRegisters int64 `json:"ctRegisters,omitempty"`
	// CtApplications 申请量（转化时间）
	CtApplications int64 `json:"ctApplications,omitempty"`
	// CtCredits 授信量（转化时间）
	CtCredits int64 `json:"ctCredits,omitempty"`
	// CtAdvisoryClueCount 留线索量（转化时间）
	CtAdvisoryClueCount int64 `json:"ctAdvisoryClueCount,omitempty"`
	// CtECShoppingCart 加入购物车量（转化时间）
	CtECShoppingCart int64 `json:"ctECShoppingCart,omitempty"`
	// CtECFavorite 商品收藏量（转化时间）
	CtECFavorite int64 `json:"ctECFavorite,omitempty"`
	// CtReserveDownloadConversions 下载（预约）按钮点击量（转化时间）
	CtReserveDownloadConversions int64 `json:"ctReserveDownloadConversions,omitempty"`
	// CtPhoneDialUpConversions 电话拨通量（转化时间）
	CtPhoneDialUpConversions int64 `json:"ctPhoneDialUpConversions,omitempty"`
	// CtShopStayConversions 店铺停留转化量（转化时间）
	CtShopStayConversions int64 `json:"ctShopStayConversions,omitempty"`
	// CtLiveWatchConversions 直播间观看量（转化时间）
	CtLiveWatchConversions int64 `json:"ctLiveWatchConversions,omitempty"`
	// CtLiveOrderConversions 直播间成单量（转化时间）
	CtLiveOrderConversions int64 `json:"ctLiveOrderConversions,omitempty"`
	// CtLiveProductClickConversions 直播间商品按钮点击量（转化时间）
	CtLiveProductClickConversions int64 `json:"ctLiveProductClickConversions,omitempty"`
	// CtLiveStayConversions 直播间停留量（转化时间）
	CtLiveStayConversions int64 `json:"ctLiveStayConversions,omitempty"`
	// CtLiveCommentConversions 直播间评论量（转化时间）
	CtLiveCommentConversions int64 `json:"ctLiveCommentConversions,omitempty"`
	// CtLiveRewardConversions 	直播间打赏量（转化时间）
	CtLiveRewardConversions int64 `json:"ctLiveRewardConversions,omitempty"`
	// CtLiveShoppingBagClickConversions 直播间购物袋点击量（转化时间）
	CtLiveShoppingBagClickConversions int64 `json:"ctLiveShoppingBagClickConversions,omitempty"`
	// CtWeixinFollowConversions 微信加粉成功量（转化时间）
	CtWeixinFollowConversions int64 `json:"ctWeixinFollowConversions,omitempty"`
	// CtProductPaySuccess 商品支付成功量（转化时间）
	CtProductPaySuccess int64 `json:"ctProductPaySuccess,omitempty"`
	// CtProductPayAmount 商品支付成功金额（转化时间）
	CtProductPayAmount float64 `json:"ctProductPayAmount,omitempty"`
	/// CtProductPayAmountROI 商品支付成功ROI（转化时间）
	CtProductPayAmountROI float64 `json:"ctProductPayAmountROI,omitempty"`
	// CtVisitStore 到店量（转化时间）
	CtVisitStore int64 `json:"ctVisitStore,omitempty"`
	// CtTalkRelatedBusiness 聊到相关业务量（转化时间）
	CtTalkRelatedBusiness int64 `json:"ctTalkRelatedBusiness,omitempty"`
	// CtReturnVisitPhoneConnect 回访-电话接通量（转化时间）
	CtReturnVisitPhoneConnect int64 `json:"ctReturnVisitPhoneConnect,omitempty"`
	// CtReturnVisitInformationConfirm 回访-信息确认量（转化时间）
	CtReturnVisitInformationConfirm int64 `json:"ctReturnVisitInformationConfirm,omitempty"`
	// CtReturnVisitFoundIntention 回访-发现意向量（转化时间）
	CtReturnVisitFoundIntention int64 `json:"ctReturnVisitFoundIntention,omitempty"`
	// CtReturnVisitHighPotentialDeal 回访-高潜成交量（转化时间）
	CtReturnVisitHighPotentialDeal int64 `json:"ctReturnVisitHighPotentialDeal,omitempty"`
	// CtReturnVisitFinishOrderClient 回访-成单客户量（转化时间）
	CtReturnVisitFinishOrderClient int64 `json:"ctReturnVisitFinishOrderClient,omitempty"`
	// CtPayReadUv 	付费阅读人数（转化时间）
	CtPayReadUv int64 `json:"ctPayReadUv,omitempty"`
	// CtPayReadAmount 付费阅读金额（转化时间）
	CtPayReadAmount float64 `json:"ctPayReadAmount,omitempty"`
	// CtPayReadAmountROI 付费阅读ROI（转化时间）
	CtPayReadAmountROI float64 `json:"ctPayReadAmountROI,omitempty"`
	// CtValidConsult 有效咨询量（转化时间）
	CtValidConsult int64 `json:"ctValidConsult,omitempty"`
	// CtAggrPageViews 营销页浏览量（转化时间）
	CtAggrPageViews int64 `json:"ctAggrPageViews,omitempty"`
	// CtWeixinAppInvokeUv 微信小程序调起人数（转化时间）
	CtWeixinAppInvokeUv int64 `json:"ctWeixinAppInvokeUv,omitempty"`
	// APP转化（转化时间）
	// CtActiveConversions 激活人数（转化时间）
	CtActiveConversions int64 `json:"ctActiveConversions,omitempty"`
	// CtRegisterUv 注册人数（转化时间）
	CtRegisterUv int64 `json:"ctRegisterUv,omitempty"`
	// CtConsumeUv 付费人数（转化时间）
	CtConsumeUv int64 `json:"ctConsumeUv,omitempty"`
	// CtConsume 付费次数（转化时间）
	CtConsume int64 `json:"ctConsume,omitempty"`
	// CtRetentions 次日留存人数（转化时间）
	CtRetentions int64 `json:"ctRetentions,omitempty"`
	// CtActiveRetentionRate 	激活次日留存率（转化时间）
	CtActiveRetentionRate float64 `json:"ctActiveRetentionRate,omitempty"`
	// CtSevenRetentions 	7日留存人数（转化时间）
	CtSevenRetentions int64 `json:"ctSevenRetentions,omitempty"`
	// CtSevenRetentionRate 	7日留存率（转化时间）
	CtSevenRetentionRate float64 `json:"ctSevenRetentionRate,omitempty"`
	// CtSevenActiveRetentions 激活7日留存率（转化时间）
	CtSevenActiveRetentions int64 `json:"ctSevenActiveRetentions,omitempty"`
	// CtThreeRetentions 3日留存人数（转化时间）
	CtThreeRetentions int64 `json:"ctThreeRetentions,omitempty"`
	// CtThreeActiveRetentionRate 激活3日留存率（转化时间）
	CtThreeActiveRetentionRate float64 `json:"ctThreeActiveRetentionRate,omitempty"`
	// CtFourRetentions 4日留存人数（转化时间）
	CtFourRetentions int64 `json:"ctFourRetentions,omitempty"`
	// CtFourActiveRetentionRate 激活4日留存率（转化时间）
	CtFourActiveRetentionRate float64 `json:"ctFourActiveRetentionRate,omitempty"`
	// CtFiveRetentions 5日留存人数（转化时间）
	CtFiveRetentions int64 `json:"ctFiveRetentions,omitempty"`
	// CtFiveActiveRetentionRate 激活5日留存率（转化时间）
	CtFiveActiveRetentionRate float64 `json:"ctFiveActiveRetentionRate,omitempty"`
	// CtSixRetentions 6日留存人数（转化时间）
	CtSixRetentions int64 `json:"ctSixRetentions,omitempty"`
	// CtSixActiveRetentionRate 激活6日留存率（转化时间）
	CtSixActiveRetentionRate float64 `json:"ctSixActiveRetentionRate,omitempty"`
	// CtFourteenRetentions 14日留存人数（转化时间）
	CtFourteenRetentions int64 `json:"ctFourteenRetentions,omitempty"`
	// CtFourteenActiveRetentionRate 激活14日留存率（转化时间）
	CtFourteenActiveRetentionRate float64 `json:"ctFourteenActiveRetentionRate,omitempty"`
	// CtAppDeepLinkRetentionRate 调起次日留存率（转化时间）
	CtAppDeepLinkRetentionRate float64 `json:"ctAppDeepLinkRetentionRate,omitempty"`
	// CtKeyBehavior 客户自定义量（转化时间）
	CtKeyBehavior int64 `json:"ctKeyBehavior,omitempty"`
	// CtDeepPageVisitConversions 关键页面浏览量（转化时间）
	CtDeepPageVisitConversions int64 `json:"ctDeepPageVisitConversions,omitempty"`
	// CtOrderSubmit 	商品下单成功量（转化时间）
	CtOrderSubmit int64 `json:"ctOrderSubmit,omitempty"`
	// CtAppDeepLinkConversions 应用调起人数（转化时间）
	CtAppDeepLinkConversions int64 `json:"ctAppDeepLinkConversions,omitempty"`
	// CtOneDayConsumeAfterActive 激活当日付费金额（转化时间）
	CtOneDayConsumeAfterActive float64 `json:"ctOneDayConsumeAfterActive,omitempty"`
	// CtOneDayConsumeAfterActiveROI 激活当日付费ROI（转化时间）
	CtOneDayConsumeAfterActiveROI float64 `json:"ctOneDayConsumeAfterActiveROI,omitempty"`
	// CtThreeDaysConsumeAfterActive 激活3日内付费金额（转化时间）
	CtThreeDaysConsumeAfterActive float64 `json:"ctThreeDaysConsumeAfterActive,omitempty"`
	// CtThreeDaysConsumeAfterActiveROI 激活3日内付费ROI（转化时间）
	CtThreeDaysConsumeAfterActiveROI float64 `json:"ctThreeDaysConsumeAfterActiveROI,omitempty"`
	// CtSevenDaysConsumeAfterActive 激活7日内付费金额（转化时间）
	CtSevenDaysConsumeAfterActive float64 `json:"ctSevenDaysConsumeAfterActive,omitempty"`
	// CtSevenDaysConsumeAfterActiveROI 激活7日内付费ROI（转化时间）
	CtSevenDaysConsumeAfterActiveROI float64 `json:"ctSevenDaysConsumeAfterActiveROI,omitempty"`
	// CtFourTeenDaysConsumeAfterActive 激活14日内付费金额（转化时间）
	CtFourTeenDaysConsumeAfterActive float64 `json:"ctFourTeenDaysConsumeAfterActive,omitempty"`
	// CtFourTeenDaysConsumeAfterActiveROI 激活14日内付费ROI（转化时间）
	CtFourTeenDaysConsumeAfterActiveROI float64 `json:"ctFourTeenDaysConsumeAfterActiveROI,omitempty"`
	// CtThirtyDaysConsumeAfterActive 激活30日内付费金额（转化时间）
	CtThirtyDaysConsumeAfterActive float64 `json:"ctThirtyDaysConsumeAfterActive,omitempty"`
	// CtThirtyDaysConsumeAfterActiveROI 激活30日内付费ROI（转化时间）
	CtThirtyDaysConsumeAfterActiveROI float64 `json:"ctThirtyDaysConsumeAfterActiveROI,omitempty"`
	// CtLoginUv 登录人数（转化时间）
	CtLoginUv int64 `json:"ctLoginUv,omitempty"`
	// CtLoginUvRetentionRate 登录次日留存率（转化时间）
	CtLoginUvRetentionRate float64 `json:"ctLoginUvRetentionRate,omitempty"`
	// CtAppPayReadUv 付费阅读人数（转化时间）
	CtAppPayReadUv int64 `json:"ctAppPayReadUv,omitempty"`
	// CtAppPayReadAmount 付费阅读金额（转化时间）
	CtAppPayReadAmount float64 `json:"ctAppPayReadAmount,omitempty"`
	// CtAppPayReadAmountROI 付费阅读ROI（转化时间）
	CtAppPayReadAmountROI float64 `json:"ctAppPayReadAmountROI,omitempty"`
	// CtAddDeskUv 添加至桌面人数（转化时间）
	CtAddDeskUv int64 `json:"ctAddDeskUv,omitempty"`
	// APP转化
	// ActiveConversions 激活人数
	ActiveConversions int64 `json:"activeConversions,omitempty"`
	// ActiveConversionsCost 激活成本
	ActiveConversionsCost float64 `json:"activeConversionsCost,omitempty"`
	// ActiveConversionsCVR 激活转化率
	ActiveConversionsCVR float64 `json:"activeConversionsCVR,omitempty"`
	// RegisterUv 注册人数
	RegisterUv int64 `json:"registerUv,omitempty"`
	// RegisterUvCost 注册成本
	RegisterUvCost float64 `json:"registerUvCost,omitempty"`
	// RegisterUvCVR 注册转化率
	RegisterUvCVR float64 `json:"registerUvCVR,omitempty"`
	// ConsumeUv 付费人数
	ConsumeUv int64 `json:"consumeUv,omitempty"`
	// ConsumeUvCost 付费成本
	ConsumeUvCost float64 `json:"consumeUvCost,omitempty"`
	// ConsumeUvCVR 付费转化率
	ConsumeUvCVR float64 `json:"consumeUvCVR,omitempty"`
	// Consume 付费次数
	Consume int64 `json:"consume,omitempty"`
	// ConsumeCost 付费成本（按次数）
	ConsumeCost float64 `json:"consumeCost,omitempty"`
	// ConsumeCVR 付费转化率（按次数）
	ConsumeCVR float64 `json:"consumeCVR,omitempty"`
	// Retentions 次日留存人数
	Retentions int64 `json:"retentions,omitempty"`
	// RetentionsCost 次日留存成本
	RetentionsCost float64 `json:"retentionsCost,omitempty"`
	// RetentionsCVR 次日留存转化率
	RetentionsCVR float64 `json:"retentionsCVR,omitempty"`
	// ActiveRetentionRate 激活次日留存率
	ActiveRetentionRate float64 `json:"activeRetentionRate,omitempty"`
	// SevenRetentions 7日留存人数
	SevenRetentions int64 `json:"sevenRetentions,omitempty"`
	// SevenRetentionsCost 7日留存成本
	SevenRetentionsCost float64 `json:"sevenRetentionsCost,omitempty"`
	// SevenRetentionsCVR 7日留存转化率
	SevenRetentionsCVR float64 `json:"sevenRetentionsCVR,omitempty"`
	// SevenActiveRetentionRate 激活7日留存率
	SevenActiveRetentionRate float64 `json:"sevenActiveRetentionRate,omitempty"`
	// ThreeRetentions 3日留存人数
	ThreeRetentions int64 `json:"threeRetentions,omitempty"`
	// ThreeRetentionsCost 3日留存成本
	ThreeRetentionsCost float64 `json:"threeRetentionsCost,omitempty"`
	// ThreeRetentionsCVR 3日留存转化率
	ThreeRetentionsCVR float64 `json:"threeRetentionsCVR,omitempty"`
	// ThreeActiveRetentionRate 激活3日留存率
	ThreeActiveRetentionRate float64 `json:"threeActiveRetentionRate,omitempty"`
	// FourRetentions 4日留存人数
	FourRetentions int64 `json:"fourRetentions,omitempty"`
	// FourRetentionsCost 4日留存成本
	FourRetentionsCost float64 `json:"fourRetentionsCost,omitempty"`
	// FourRetentionsCVR 4日留存转化率
	FourRetentionsCVR float64 `json:"fourRetentionsCVR,omitempty"`
	// FourActiveRetentionRate 激活4日留存率
	FourActiveRetentionRate float64 `json:"fourActiveRetentionRate,omitempty"`
	// FiveRetentions 5日留存人数
	FiveRetentions int64 `json:"fiveRetentions,omitempty"`
	// FiveRetentionsCost 5日留存成本
	FiveRetentionsCost float64 `json:"fiveRetentionsCost,omitempty"`
	// FiveRetentionsCVR 5日留存转化率
	FiveRetentionsCVR float64 `json:"fiveRetentionsCVR,omitempty"`
	// FiveActiveRetentionRate 激活5日留存率
	FiveActiveRetentionRate float64 `json:"fiveActiveRetentionRate,omitempty"`
	// SixRetentions 6日留存人数
	SixRetentions int64 `json:"sixRetentions,omitempty"`
	// SixRetentionsCost 6日留存成本
	SixRetentionsCost float64 `json:"sixRetentionsCost,omitempty"`
	// SixRetentionsCVR 6日留存转化率
	SixRetentionsCVR float64 `json:"sixRetentionsCVR,omitempty"`
	// SixActiveRetentionRate 激活6日留存率
	SixActiveRetentionRate float64 `json:"sixActiveRetentionRate,omitempty"`
	// FourteenRetentions 14日留存人数
	FourteenRetentions int64 `json:"fourteenRetentions,omitempty"`
	// FourteenRetentionsCost 14日留存成本
	FourteenRetentionsCost float64 `json:"fourteenRetentionsCost,omitempty"`
	// FourteenRetentionsCVR 14日留存转化率
	FourteenRetentionsCVR float64 `json:"fourteenRetentionsCVR,omitempty"`
	// FourteenActiveRetentionRate 激活14日留存率
	FourteenActiveRetentionRate float64 `json:"fourteenActiveRetentionRate,omitempty"`
	// AppDeepLinkRetentionRate 调起次日留存率
	AppDeepLinkRetentionRate float64 `json:"appDeepLinkRetentionRate,omitempty"`
	// KeyBehavior 客户自定义量
	KeyBehavior string `json:"keyBehavior,omitempty"`
	// KeyBehaviorCost 客户自定义成本
	KeyBehaviorCost float64 `json:"keyBehaviorCost,omitempty"`
	// KeyBehaviorCVR 客户自定义转化率
	KeyBehaviorCVR float64 `json:"keyBehaviorCVR,omitempty"`
	// DeepPageVisitConversions 关键页面浏览量
	DeepPageVisitConversions int64 `json:"deepPageVisitConversions,omitempty"`
	// DeepPageVisitConversionsCost 关键页面浏览成本
	DeepPageVisitConversionsCost float64 `json:"deepPageVisitConversionsCost,omitempty"`
	// DeepPageVisitConversionsCVR 关键页面浏览转化率
	DeepPageVisitConversionsCVR float64 `json:"deepPageVisitConversionsCVR,omitempty"`
	// OrderSubmit 商品下单成功量
	OrderSubmit int64 `json:"orderSubmit,omitempty"`
	// DeepOrderSubmitCost 商品下单成功成本
	DeepOrderSubmitCost float64 `json:"deepOrderSubmitCost,omitempty"`
	// OrderSubmitCVR 商品下单成功转化率
	OrderSubmitCVR float64 `json:"orderSubmitCVR,omitempty"`
	// AppDeepLinkConversions 应用调起人数
	AppDeepLinkConversions int64 `json:"appDeepLinkConversions,omitempty"`
	// AppDeepLinkConversionsCost 应用调起成本
	AppDeepLinkConversionsCost float64 `json:"appDeepLinkConversionsCost,omitempty"`
	// AppDeepLinkConversionsCVR 应用调起转化率
	AppDeepLinkConversionsCVR float64 `json:"appDeepLinkConversionsCVR,omitempty"`
	// OneDayConsumeAfterActive 激活当日付费金额
	OneDayConsumeAfterActive float64 `json:"oneDayConsumeAfterActive,omitempty"`
	// OneDayConsumeAfterActiveROI 激活当日付费ROI
	OneDayConsumeAfterActiveROI float64 `json:"oneDayConsumeAfterActiveROI,omitempty"`
	// ThreeDaysConsumeAfterActive 激活3日内付费金额
	ThreeDaysConsumeAfterActive float64 `json:"threeDaysConsumeAfterActive,omitempty"`
	// ThreeDaysConsumeAfterActiveROI 激活3日内付费ROI
	ThreeDaysConsumeAfterActiveROI float64 `json:"threeDaysConsumeAfterActiveROI,omitempty"`
	// SevenDaysConsumeAfterActive 激活7日内付费金额
	SevenDaysConsumeAfterActive float64 `json:"sevenDaysConsumeAfterActive,omitempty"`
	// SevenDaysConsumeAfterActiveROI 激活7日内付费ROI
	SevenDaysConsumeAfterActiveROI float64 `json:"sevenDaysConsumeAfterActiveROI,omitempty"`
	// FourteenDaysConsumeAfterActive 激活14日内付费金额
	FourteenDaysConsumeAfterActive float64 `json:"fourteenDaysConsumeAfterActive,omitempty"`
	// FourteenDaysConsumeAfterActiveROI 激活14日内付费ROI
	FourteenDaysConsumeAfterActiveROI float64 `json:"fourteenDaysConsumeAfterActiveROI,omitempty"`
	// ThirtyDaysConsumeAfterActive 激活30日内付费金额
	ThirtyDaysConsumeAfterActive float64 `json:"thirtyDaysConsumeAfterActive,omitempty"`
	// ThirtyDaysConsumeAfterActiveROI 激活30日内付费ROI
	ThirtyDaysConsumeAfterActiveROI float64 `json:"thirtyDaysConsumeAfterActiveROI,omitempty"`
	// AppCredits 授信量
	AppCredits int64 `json:"appCredits,omitempty"`
	// AppCreditsCost 授信成本
	AppCreditsCost float64 `json:"appCreditsCost,omitempty"`
	// AppCreditsCVR 授信转化率
	AppCreditsCVR float64 `json:"appCreditsCVR,omitempty"`
	// AppRegisterPayRate 注册付费率
	AppRegisterPayRate float64 `json:"appRegisterPayRate,omitempty"`
	// AppRegisterECBuyRate 注册下单率
	AppRegisterECBuyRate float64 `json:"appRegisterECBuyRate,omitempty"`
	// LoginUv 登录人数
	LoginUv int64 `json:"loginUv,omitempty"`
	// LoginUvCost 登录成本
	LoginUvCost float64 `json:"loginUvCost,omitempty"`
	// LoginUvCVR 登录转化率
	LoginUvCVR float64 `json:"loginUvCVR,omitempty"`
	// AppPayReadUv 付费阅读人数
	AppPayReadUv int64 `json:"appPayReadUv,omitempty"`
	// AppPayReadUvCost 付费阅读成本
	AppPayReadUvCost float64 `json:"appPayReadUvCost,omitempty"`
	// AppPayReadUvCVR 付费阅读转化率
	AppPayReadUvCVR float64 `json:"appPayReadUvCVR,omitempty"`
	// AppPayReadAmount 付费阅读金额
	AppPayReadAmount float64 `json:"appPayReadAmount,omitempty"`
	// AppPayReadAmountROI 付费阅读ROI
	AppPayReadAmountROI float64 `json:"appPayReadAmountROI,omitempty"`
	// AddDeskUv 添加至桌面人数
	AddDeskUv int64 `json:"addDeskUv,omitempty"`
	// AddDeskUvCost 添加至桌面成本
	AddDeskUvCost float64 `json:"addDeskUvCost,omitempty"`
	// AddDeskUvCVR 添加至桌面转化率
	AddDeskUvCVR float64 `json:"addDeskUvCVR,omitempty"`
	// 小程序转化
	// AggrMiniProgramFormSubmit 表单提交成功量
	AggrMiniProgramFormSubmit int64 `json:"aggrMiniProgramFormSubmit,omitempty"`
	// AggrMiniProgramFormSubmitCost 表单提交成本
	AggrMiniProgramFormSubmitCost float64 `json:"aggrMiniProgramFormSubmitCost,omitempty"`
	// AggrMiniProgramFormSubmitCVR 表单提交转化率
	AggrMiniProgramFormSubmitCVR float64 `json:"aggrMiniProgramFormSubmitCVR,omitempty"`
	// MpOrderSuccess 商品下单成功量
	MpOrderSuccess int64 `json:"mpOrderSuccess,omitempty"`
	// MpOrderSuccessCost 商品下单成本
	MpOrderSuccessCost float64 `json:"mpOrderSuccessCost,omitempty"`
	// MpOrderSuccessCVR 商品下单转化率
	MpOrderSuccessCVR float64 `json:"mpOrderSuccessCVR,omitempty"`
	// MpCallButtonClicks 电话按钮点击量
	MpCallButtonClicks int64 `json:"mpCallButtonClicks,omitempty"`
	// MpCallButtonClicksCost 电话按钮点击成本
	MpCallButtonClicksCost float64 `json:"mpCallButtonClicksCost,omitempty"`
	// MpCallButtonClicksCVR 电话按钮点击转化率
	MpCallButtonClicksCVR float64 `json:"mpCallButtonClicksCVR,omitempty"`
	// MpEffectiveConsults 一句话咨询量
	MpEffectiveConsults int64 `json:"mpEffectiveConsults,omitempty"`
	// MpEffectiveConsultsCost 一句话咨询成本
	MpEffectiveConsultsCost float64 `json:"mpEffectiveConsultsCost,omitempty"`
	// MpEffectiveConsultsCVR 一句话咨询转化率
	MpEffectiveConsultsCVR float64 `json:"mpEffectiveConsultsCVR,omitempty"`
	// MpThreeConsults 三句话咨询量
	MpThreeConsults int64 `json:"mpThreeConsults,omitempty"`
	// MpThreeConsultsCost 三句话咨询成本
	MpThreeConsultsCost float64 `json:"mpThreeConsultsCost,omitempty"`
	// MpThreeConsultsCVR 三句话咨询转化率
	MpThreeConsultsCVR float64 `json:"mpThreeConsultsCVR,omitempty"`
	// MpOrderSubmitSuccess 订单提交成功量
	MpOrderSubmitSuccess int64 `json:"mpOrderSubmitSuccess,omitempty"`
	// MpOrderSubmitSuccessCost 订单提交成本
	MpOrderSubmitSuccessCost float64 `json:"mpOrderSubmitSuccessCost,omitempty"`
	// MpOrderSubmitSuccessCVR 订单提交转化率
	MpOrderSubmitSuccessCVR float64 `json:"mpOrderSubmitSuccessCVR,omitempty"`
	// MpOrderSubmitSuccessAmount 订单提交成功金额
	MpOrderSubmitSuccessAmount float64 `json:"mpOrderSubmitSuccessAmount,omitempty"`
	// MpOrderSubmitSuccessAmountROI 订单提交成功ROI
	MpOrderSubmitSuccessAmountROI float64 `json:"mpOrderSubmitSuccessAmountROI,omitempty"`
	// MpPayReadUv 付费阅读人数
	MpPayReadUv int64 `json:"mpPayReadUv,omitempty"`
	// MpPayReadUvCost 付费阅读成本
	MpPayReadUvCost float64 `json:"mpPayReadUvCost,omitempty"`
	// MpPayReadUvCVR 付费阅读转化率
	MpPayReadUvCVR float64 `json:"mpPayReadUvCVR,omitempty"`
	// MpPayReadAmount 付费阅读金额
	MpPayReadAmount float64 `json:"mpPayReadAmount,omitempty"`
	// MpPayReadAmountROI 付费阅读ROI
	MpPayReadAmountROI float64 `json:"mpPayReadAmountROI,omitempty"`
	// MpAddDeskUv 添加至桌面人数
	MpAddDeskUv int64 `json:"mpAddDeskUv,omitempty"`
	// MpAddDeskUvCost 添加至桌面成本
	MpAddDeskUvCost float64 `json:"mpAddDeskUvCost,omitempty"`
	// MpAddDeskUvCVR 添加至桌面转化率
	MpAddDeskUvCVR float64 `json:"mpAddDeskUvCVR,omitempty"`
	// MpBaiduInvokeUv 百度小程序调起人数
	MpBaiduInvokeUv int64 `json:"mpBaiduInvokeUv,omitempty"`
	// MpBaiduInvokeUvCost 百度小程序调起成本
	MpBaiduInvokeUvCost float64 `json:"mpBaiduInvokeUvCost,omitempty"`
	// MpBaiduInvokeUvCVR 百度小程序调起转化率
	MpBaiduInvokeUvCVR float64 `json:"mpBaiduInvokeUvCVR,omitempty"`
	// 小程序转化（转化时间）
	// CtAggrMiniProgramFormSubmit 表单提交成功量（转化时间）
	CtAggrMiniProgramFormSubmit int64 `json:"ctAggrMiniProgramFormSubmit,omitempty"`
	// CtMpOrderSuccess 商品下单成功量（转化时间）
	CtMpOrderSuccess int64 `json:"ctMpOrderSuccess,omitempty"`
	// CtMpCallButtonClicks 电话按钮点击量（转化时间）
	CtMpCallButtonClicks int64 `json:"ctMpCallButtonClicks,omitempty"`
	// CtMpEffectiveConsults 一句话咨询量（转化时间）
	CtMpEffectiveConsults int64 `json:"ctMpEffectiveConsults,omitempty"`
	// CtMpThreeConsults 三句话咨询量（转化时间）
	CtMpThreeConsults int64 `json:"ctMpThreeConsults,omitempty"`
	// CtMpOrderSubmitSuccess 订单提交成功量（转化时间）
	CtMpOrderSubmitSuccess int64 `json:"ctMpOrderSubmitSuccess,omitempty"`
	// CtMpOrderSubmitSuccessAmount 订单提交成功金额（转化时间）
	CtMpOrderSubmitSuccessAmount float64 `json:"ctMpOrderSubmitSuccessAmount,omitempty"`
	// CtMpOrderSubmitSuccessAmountROI 订单提交成功ROI（转化时间）
	CtMpOrderSubmitSuccessAmountROI float64 `json:"ctMpOrderSubmitSuccessAmountROI,omitempty"`
	// CtMpPayReadUv 付费阅读人数（转化时间）
	CtMpPayReadUv int64 `json:"ctMpPayReadUv,omitempty"`
	// CtMpPayReadAmount 付费阅读金额（转化时间）
	CtMpPayReadAmount float64 `json:"ctMpPayReadAmount,omitempty"`
	// CtMpPayReadAmountROI 付费阅读ROI（转化时间）
	CtMpPayReadAmountROI float64 `json:"ctMpPayReadAmountROI,omitempty"`
	// CtMpAddDeskUv 添加至桌面人数（转化时间）
	CtMpAddDeskUv int64 `json:"ctMpAddDeskUv,omitempty"`
	// CtMpAddDeskUvCost 添加至桌面成本（转化时间）
	CtMpAddDeskUvCost float64 `json:"ctMpAddDeskUvCost,omitempty"`
	// CtMpBaiduInvokeUv 百度小程序调起人数（转化时间）
	CtMpBaiduInvokeUv int64 `json:"ctMpBaiduInvokeUv,omitempty"`
	// 行业转化
	// FeedOCPCConversionsDetail118Uv 付费观剧人数
	FeedOCPCConversionsDetail118Uv int64 `json:"feedOCPCConversionsDetail118Uv,omitempty"`
	// AggrPayWatchUvCost 付费观剧成本
	AggrPayWatchUvCost float64 `json:"aggrPayWatchUvCost,omitempty"`
	// AggrPayWatchUvCVR 付费观剧转化率
	AggrPayWatchUvCVR float64 `json:"aggrPayWatchUvCVR,omitempty"`
	// CtFeedOCPCConversionsDetail118Uv 付费观剧人数（转化时间）
	CtFeedOCPCConversionsDetail118Uv int64 `json:"ctFeedOCPCConversionsDetail118Uv,omitempty"`
	// OneDayAggrPayWatchAmount 付费观剧当日内金额
	OneDayAggrPayWatchAmount float64 `json:"oneDayAggrPayWatchAmount,omitempty"`
	// ThreeDayAggrPayWatchAmount 付费观剧三日内金额
	ThreeDayAggrPayWatchAmount float64 `json:"threeDayAggrPayWatchAmount,omitempty"`
	// SevenDayAggrPayWatchAmount 付费观剧七日内金额
	SevenDayAggrPayWatchAmount float64 `json:"sevenDayAggrPayWatchAmount,omitempty"`
	// FourteenDayAggrPayWatchAmount 付费观剧十四日内金额
	FourteenDayAggrPayWatchAmount float64 `json:"fourteenDayAggrPayWatchAmount,omitempty"`
	// ThirtyDayAggrPayWatchAmount 付费观剧三十日内金额
	ThirtyDayAggrPayWatchAmount float64 `json:"thirtyDayAggrPayWatchAmount,omitempty"`
	// CtOneDayAggrPayWatchAmount 付费观剧当日内金额（转化时间）
	CtOneDayAggrPayWatchAmount float64 `json:"ctOneDayAggrPayWatchAmount,omitempty"`
	// CtThreeDayAggrPayWatchAmount 付费观剧三日内金额（转化时间）
	CtThreeDayAggrPayWatchAmount float64 `json:"ctThreeDayAggrPayWatchAmount,omitempty"`
	// CtSevenDayAggrPayWatchAmount 付费观剧七日内金额（转化时间）
	CtSevenDayAggrPayWatchAmount float64 `json:"ctSevenDayAggrPayWatchAmount,omitempty"`
	// CtFourteenDayAggrPayWatchAmount 付费观剧十四日内金额（转化时间）
	CtFourteenDayAggrPayWatchAmount float64 `json:"ctFourteenDayAggrPayWatchAmount,omitempty"`
	// CtThirtyDayAggrPayWatchAmount 付费观剧三十日内金额（转化时间）
	CtThirtyDayAggrPayWatchAmount float64 `json:"ctThirtyDayAggrPayWatchAmount,omitempty"`
	// OneDayAggrPayWatchAmountROI 付费观剧当日内ROI
	OneDayAggrPayWatchAmountROI float64 `json:"oneDayAggrPayWatchAmountROI,omitempty"`
	// ThreeDayAggrPayWatchAmountROI 付费观剧三日内ROI
	ThreeDayAggrPayWatchAmountROI float64 `json:"threeDayAggrPayWatchAmountROI,omitempty"`
	// SevenDayAggrPayWatchAmountROI 付费观剧七日内ROI
	SevenDayAggrPayWatchAmountROI float64 `json:"sevenDayAggrPayWatchAmountROI,omitempty"`
	// FourteenDayAggrPayWatchAmountROI 付费观剧十四日内ROI
	FourteenDayAggrPayWatchAmountROI float64 `json:"fourteenDayAggrPayWatchAmountROI,omitempty"`
	// ThirtyDayAggrPayWatchAmountROI 付费观剧三十日内ROI
	ThirtyDayAggrPayWatchAmountROI float64 `json:"thirtyDayAggrPayWatchAmountROI,omitempty"`
	// CtOneDayAggrPayWatchAmountROI 付费观剧当日内ROI（转化时间）
	CtOneDayAggrPayWatchAmountROI float64 `json:"ctOneDayAggrPayWatchAmountROI,omitempty"`
	// CtThreeDayAggrPayWatchAmountROI 付费观剧三日内ROI（转化时间）
	CtThreeDayAggrPayWatchAmountROI float64 `json:"ctThreeDayAggrPayWatchAmountROI,omitempty"`
	// CtSevenDayAggrPayWatchAmountROI 付费观剧七日内ROI（转化时间）
	CtSevenDayAggrPayWatchAmountROI float64 `json:"ctSevenDayAggrPayWatchAmountROI,omitempty"`
	// CtFourteenDayAggrPayWatchAmountROI 付费观剧十四日内ROI（转化时间）
	CtFourteenDayAggrPayWatchAmountROI float64 `json:"ctFourteenDayAggrPayWatchAmountROI,omitempty"`
	// CtThirtyDayAggrPayWatchAmountROI 付费观剧三十日内ROI（转化时间）
	CtThirtyDayAggrPayWatchAmountROI float64 `json:"ctThirtyDayAggrPayWatchAmountROI,omitempty"`
}
